trigger:
- main

pr:
  drafts: false
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest
steps:
- script: npm install
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build'

- script: npm run lint
  displayName: 'Lint'

- script: npm pack
  displayName: 'Pack'
